services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["yarn", "run", "start"]
    ports:
      - "3001:3001"
    volumes:
      - .:/AlgorithmWikiAPI
    env_file:
      - .env
